### ISSUE TITLE
[devops] Error while deploying : cache error

### ISSUE THREAD

**Issue by odelcroi** [tchapgouv/tchap-identite#87]
An error with distributed cache occurs when deploying a new version.

It seems that the new container tries to sync its cache with the old container, which leads to an error.

```
2022-06-20 19:41:46,350 INFO  [io.quarkus.deployment.QuarkusAugmentor] (main) Quarkus augmentation completed in 9629ms
2022-06-20 21:41:46.375386823 +0200 CEST [web-1] Server configuration updated and persisted. Run the following command to review the configuration:
2022-06-20 21:41:46.375545309 +0200 CEST [web-1] 	kc.sh show-config
2022-06-20 21:41:46.376766341 +0200 CEST [web-1] Next time you run the server, just run:
2022-06-20 21:41:46.376768882 +0200 CEST [web-1] 	kc.sh start
2022-06-20 21:41:46.431832149 +0200 CEST [web-1] Picked up JAVA_TOOL_OPTIONS: -XX:+UseContainerSupport -Xmx300m -Xss512k -XX:CICompilerCount=2 -Dfile.encoding=UTF-8
2022-06-20 21:41:48.859645990 +0200 CEST [web-1] SLF4J: Class path contains multiple SLF4J bindings.
2022-06-20 21:41:48.859656256 +0200 CEST [web-1] SLF4J: Found binding in [jar:file:/app/keycloak/lib/lib/main/org.jboss.slf4j.slf4j-jboss-logmanager-1.1.0.Final.jar!/org/slf4j/impl/StaticLoggerBinder.class]
2022-06-20 21:41:48.859657578 +0200 CEST [web-1] SLF4J: Found binding in [jar:file:/app/keycloak/lib/../providers/tchap-identite.jar!/org/slf4j/impl/StaticLoggerBinder.class]
2022-06-20 21:41:48.859658587 +0200 CEST [web-1] SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
2022-06-20 21:41:48.860013738 +0200 CEST [web-1] SLF4J: Actual binding is of type [org.slf4j.impl.Slf4jLoggerFactory]
2022-06-20 21:41:49.634407657 +0200 CEST [web-1] 2022-06-20 19:41:49,631 INFO  [org.keycloak.quarkus.runtime.hostname.DefaultHostnameProvider] (main) Hostname settings: FrontEnd: app.authentification.beta.gouv.fr, Strict HTTPS: true, Path: <request>, Strict BackChannel: true, Admin: <request>, Port: -1, Proxied: true
2022-06-20 21:41:50.472497051 +0200 CEST [web-1] 2022-06-20 19:41:50,471 WARN  [org.infinispan.CONFIG] (keycloak-cache-init) ISPN000569: Unable to persist Infinispan internal caches as no global state enabled
2022-06-20 21:41:50.505914067 +0200 CEST [web-1] 2022-06-20 19:41:50,505 WARN  [org.infinispan.PERSISTENCE] (keycloak-cache-init) ISPN000554: jboss-marshalling is deprecated and planned for removal
2022-06-20 21:41:50.520725527 +0200 CEST [web-1] 2022-06-20 19:41:50,520 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000556: Starting user marshaller 'org.infinispan.jboss.marshalling.core.JBossUserMarshaller'
2022-06-20 21:41:50.769224931 +0200 CEST [web-1] 2022-06-20 19:41:50,768 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000128: Infinispan version: Infinispan 'Triskaidekaphobia' 13.0.9.Final
2022-06-20 21:41:50.999431834 +0200 CEST [web-1] 2022-06-20 19:41:50,998 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000078: Starting JGroups channel `ISPN`
2022-06-20 21:41:50.999439150 +0200 CEST [web-1] 2022-06-20 19:41:50,999 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000088: Unable to use any JGroups configuration mechanisms provided in properties {}. Using default JGroups configuration!
2022-06-20 21:41:51.085626443 +0200 CEST [web-1] 2022-06-20 19:41:51,085 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the send buffer of socket MulticastSocket was set to 1.00MB, but the OS only allocated 212.99KB
2022-06-20 21:41:51.085901855 +0200 CEST [web-1] 2022-06-20 19:41:51,085 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the receive buffer of socket MulticastSocket was set to 20.00MB, but the OS only allocated 212.99KB
2022-06-20 21:41:51.085905635 +0200 CEST [web-1] 2022-06-20 19:41:51,085 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the send buffer of socket MulticastSocket was set to 1.00MB, but the OS only allocated 212.99KB
2022-06-20 21:41:51.086140354 +0200 CEST [web-1] 2022-06-20 19:41:51,085 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the receive buffer of socket MulticastSocket was set to 25.00MB, but the OS only allocated 212.99KB
2022-06-20 21:41:51.161841543 +0200 CEST [web-1] 2022-06-20 19:41:51,161 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000079: Channel `ISPN` local address is `tchap-id-prod-web-1-57520`, physical addresses are `[172.17.0.11:45356]`
2022-06-20 21:41:51.153174025 +0200 CEST [web-1] 2022-06-20 19:41:51,152 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000094: Received new cluster view for channel ISPN: [auth-reva-beta-gouv-fr-web-1-1267|7] (2) [auth-reva-beta-gouv-fr-web-1-1267, tchap-id-prod-web-1-57520]
2022-06-20 21:41:51.554547107 +0200 CEST [web-1] 	at org.infinispan.statetransfer.InboundTransferTask.lambda$startTransfer$3(InboundTransferTask.java:167)
2022-06-20 21:41:51.554543774 +0200 CEST [web-1] 2022-06-20 19:41:51,552 WARN  [org.infinispan.statetransfer.InboundTransferTask] (jgroups-8,tchap-id-prod-web-1-57520) ISPN000210: Failed to request state of cache authenticationSessions from node auth-reva-beta-gouv-fr-web-1-1267, segments {0-255}: org.infinispan.commons.CacheException: ExceptionResponse(java.io.EOFException)
2022-06-20 21:41:51.554547772 +0200 CEST [web-1] 	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:930)
2022-06-20 21:41:51.554550327 +0200 CEST [web-1] 	at org.infinispan.remoting.transport.impl.SingleTargetRequest.onResponse(SingleTargetRequest.java:46)
2022-06-20 21:41:51.554549891 +0200 CEST [web-1] 	at org.infinispan.remoting.transport.AbstractRequest.complete(AbstractRequest.java:67)
2022-06-20 21:41:51.554549483 +0200 CEST [web-1] 	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
2022-06-20 21:41:51.554549058 +0200 CEST [web-1] 	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
2022-06-20 21:41:51.554548611 +0200 CEST [web-1] 	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:907)
2022-06-20 21:41:51.554551423 +0200 CEST [web-1] 	at org.infinispan.remoting.transport.jgroups.JGroupsTransport.processMessage(JGroupsTransport.java:1397)
2022-06-20 21:41:51.554551078 +0200 CEST [web-1] 	at org.infinispan.remoting.transport.jgroups.JGroupsTransport.processResponse(JGroupsTransport.java:1495)
2022-06-20 21:41:51.554550746 +0200 CEST [web-1] 	at org.infinispan.remoting.transport.impl.RequestRepository.addResponse(RequestRepository.java:51)
2022-06-20 21:41:51.554769408 +0200 CEST [web-1] 	at org.jgroups.protocols.pbcast.STABLE.up(STABLE.java:254)
2022-06-20 21:41:51.554769056 +0200 CEST [web-1] 	at org.jgroups.protocols.pbcast.GMS.up(GMS.java:876)
2022-06-20 21:41:51.554768627 +0200 CEST [web-1] 	at org.jgroups.protocols.FlowControl.up(FlowControl.java:347)
2022-06-20 21:41:51.554768188 +0200 CEST [web-1] 	at org.jgroups.protocols.FlowControl.up(FlowControl.java:347)
2022-06-20 21:41:51.554767157 +0200 CEST [web-1] 	at org.jgroups.protocols.FRAG3.up(FRAG3.java:165)
2022-06-20 21:41:51.554552793 +0200 CEST [web-1] 	at org.jgroups.stack.ProtocolStack.up(ProtocolStack.java:913)
2022-06-20 21:41:51.554552469 +0200 CEST [web-1] 	at org.jgroups.JChannel.up(JChannel.java:780)
2022-06-20 21:41:51.554552063 +0200 CEST [web-1] 	at org.infinispan.remoting.transport.jgroups.JGroupsTransport$ChannelCallbacks.up(JGroupsTransport.java:1582)
2022-06-20 21:41:51.554551739 +0200 CEST [web-1] 	at org.infinispan.remoting.transport.jgroups.JGroupsTransport.access$300(JGroupsTransport.java:145)
2022-06-20 21:41:51.554772990 +0200 CEST [web-1] 	at org.jgroups.protocols.FD_SOCK.up(FD_SOCK.java:254)
2022-06-20 21:41:51.554772668 +0200 CEST [web-1] 	at org.jgroups.protocols.FailureDetection.up(FailureDetection.java:186)
2022-06-20 21:41:51.554772227 +0200 CEST [web-1] 	at org.jgroups.protocols.VERIFY_SUSPECT.up(VERIFY_SUSPECT.java:132)
2022-06-20 21:41:51.554771803 +0200 CEST [web-1] 	at org.jgroups.protocols.pbcast.NAKACK2.up(NAKACK2.java:592)
2022-06-20 21:41:51.554771378 +0200 CEST [web-1] 	at org.jgroups.protocols.UNICAST3.up(UNICAST3.java:405)
2022-06-20 21:41:51.554770622 +0200 CEST [web-1] 	at org.jgroups.protocols.UNICAST3.handleDataReceived(UNICAST3.java:752)
2022-06-20 21:41:51.554770183 +0200 CEST [web-1] 	at org.jgroups.protocols.UNICAST3.addMessage(UNICAST3.java:771)
2022-06-20 21:41:51.554769749 +0200 CEST [web-1] 	at org.jgroups.protocols.UNICAST3.deliverMessage(UNICAST3.java:1048)
2022-06-20 21:41:51.554775652 +0200 CEST [web-1] 	at java.base/java.lang.Thread.run(Thread.java:829)
2022-06-20 21:41:51.554775239 +0200 CEST [web-1] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2022-06-20 21:41:51.554774775 +0200 CEST [web-1] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2022-06-20 21:41:51.554774376 +0200 CEST [web-1] 	at org.jgroups.util.SubmitToThreadPool$SingleMessageHandler.run(SubmitToThreadPool.java:98)
2022-06-20 21:41:51.554773956 +0200 CEST [web-1] 	at org.jgroups.protocols.TP.passMessageUp(TP.java:1400)
2022-06-20 21:41:51.554773638 +0200 CEST [web-1] 	at org.jgroups.protocols.Discovery.up(Discovery.java:300)
2022-06-20 21:41:51.554773319 +0200 CEST [web-1] 	at org.jgroups.protocols.MERGE3.up(MERGE3.java:281)
2022-06-20 21:43:07.979009555 +0200 CEST [manager] container [web-1] (62b0cd5acc40e1d51422d436) has stopped
```

**Comment by odelcroi** [comment]
## Temporary workaround 
Disable distributed cache by setting KC_CACHE=local.

`2022-06-20 22:03:09.467611808 +0200 CEST[web-1] 2022-06-20 20:03:09,466 INFO [org.infinispan.CLUSTER] (Thread-22) ISPN000080: Disconnecting JGroups channel `ISPN`
`
